/* 다음은 식품의 정보를 담은 FOOD_PRODUCT 테이블이다. FOOD_PRODUCT 테이블은
다음과 같으며 PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE는
식품 ID, 식품 이름, 식품 코드, 식품 분류, 식품 가격을 의미한다
Column name / Tyep / Nullable
PRODUCT_ID / VARCHAR(10) / FALSE
PRODUCT_NAME / VARCHAR(50) / FALSE
PRODUCT_CD / VARCHAR(10) / TRUE
CATEGORY / VARCHAR(10) / TRUE
PRICE / NUMBER / TRUE
FOOD_PRODUCT 테이블에서 가격이 제일 비싼 식품의 식품 ID, 식품 이름, 식품 코드, 식품분류,
식품 가격을 조회하는 SQL문을 작성하라 */

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
);


SELECT *
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1;